### ISSUE TITLE
review my app

### ISSUE THREAD

**Issue by swetakadam** [swetakadam/MyToDo#1]
My App as part of pre-work is complete @codepathreview @codepath
![mytododemo](https://cloud.githubusercontent.com/assets/5216040/16219905/453ca850-373e-11e6-832a-5caacb658369.gif)

**Comment by nesquena** [comment]
Sweta,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose an available 15-minute slot in the mornings or evenings. Let us know if none of those times work.

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app.

Once you select a slot, can you make sure to **include the best number** to reach you at to the invite?

**Prior to our chat**, can you take some time to research the most common Android Activity lifecycle methods as well as the `ArrayAdapter` pattern used when working with lists? We will be discussing these topics with you conceptually in the phone call. We encourage you to [search our guides](http://guides.codepath.com/android/) as well as any other sources you'd like.

Look forward to chatting soon!

**Comment by swetakadam** [comment]
Thank you Nathan --- that sounds great ... I will work on extension assignment.
It is really great that the code will be reviewed

**Comment by swetakadam** [comment]
@nesquena  - I added content provider and pushed my changes  .. however I have to hook up it to UI and do few more things  .. in case you wish to take a look

**Comment by swetakadam** [comment]
Added Test classes for testing Content provider

**Comment by swetakadam** [comment]
@nesquena  -- I have added dialog fragment and many more things -- need to hook up everything together .. will keep you posted .. Thanks

**Comment by nesquena** [comment]
Okay great thanks for the update, let us know when we should take another look.

**Comment by swetakadam** [comment]
1Added Custom CursorAdapter , custom view for list , using ContentProvider to persist data in database, background thread (can be refined further) 
![mytodo-part2](https://cloud.githubusercontent.com/assets/5216040/16638383/bc57fe62-439b-11e6-961f-eb0181c8e6e2.gif)

**Comment by swetakadam** [comment]
@nesquena  -- I just added another GIF to give you a quick review .. I will be completing the edit screen .. hopefully tonight and will tag you again for complete code review .. Thank you for getting back

**Comment by swetakadam** [comment]
@nesquena @codepathreview @codepath - I have finished doing to add on work .. Please review my App ...

Few things to fix 
1. code re-fractor 
2. better design for date select 

Here is final GIF 

![mytodo-part3](https://cloud.githubusercontent.com/assets/5216040/16699782/0b98f7ae-450b-11e6-933e-be46162a4a90.gif)

**Comment by nesquena** [comment]
Thanks! We'll be following up again very soon as we finish final admissions.
